### ISSUE TITLE
downstream side?

### ISSUE THREAD

**Issue by igor-telxira** [apostvav/kannel_exporter#16]
Hi, thanks for the tool, really usefull. 

This exporter only takes the stats from bearerbox (upstrem side), Have you been considering to monitor ESME (smppbox) side too ?

Thanks you 
Igor

**Comment by apostvav** [comment]
Hi Igor, thanks for your kind words. This exporter scrapes the bearerbox status page and exports the available metrics. smppbox would require a new exporter (probably some code could be shared) since it's a different application which requires a licence too. I do not have any access to this software.
